services:
  web:
   build: . 
   restart: always
   depends_on:
     - db
   ports:
     - "80:80"
   volumes:
     - ./:/var/www/html/
   links:
     - db
  db:
    image: mariadb
    restart: always
    volumes:
      - ./db_sql_script/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: bssdb
    ports:
      - "3306:3306"
