services:
  db:
    image: mariadb
    restart: always
    volumes:
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: eshop
    ports:
      - "3306:3306"
